# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-05-11 21:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('image_name', models.CharField(max_length=30)),
                ('image_description', models.TextField(max_length=200)),
                ('photo_date', models.DateTimeField(auto_now_add=True)),
                ('image_category', models.ManyToManyField(to='image.category')),
                ('image_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image.location')),
                ('photography', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image.Photographer')),
            ],
        ),
    ]
